upto page 19
vishvAsa/AgamaH pull request #13
Opened 2022-12-02 08:05 UTC by Dhunee

प्रतिपृष्ठं व्याख्यानस्यासमाप्तावपि योजितं </detail> इत्यादिकं निवारितम् । अतः प्रथमपृष्ठादारभ्यैव परिवर्तनमारोपितायामस्यां सञ्चिकायां नवदशपृष्ठपर्यन्तं सन्दृश्यते ।

2022-12-02 08:28 UTC, vvasuki requested changes

2022-12-02 08:28 UTC, vvasuki commented on AryaH/hinduism/branches/vaiShNavaH/shrI-sampradAyaH/kriyA/gopAla-deshikaH/Ahnikam_AhnikArtha-prakAshikA/01_praveshaH.md
> +इति । न च भगवत्प्रभृतिस्वाचार्यपर्यन्तं तत्क्रमेण गुरुपङ्क्तिभजनं कार्यं “लक्ष्मीनाथसमारम्भां” कमप्याद्यं गुरुं वन्दे” इत्यादौ तथा दर्शनादाचाराच्चेति वाच्यम् - उक्ततृतीयाधिकारे “गुरून् प्रपद्य प्रथमं
"कमप्याद्यं इति स्यात्?

2022-12-02 08:28 UTC, vvasuki commented on AryaH/hinduism/branches/vaiShNavaH/shrI-sampradAyaH/kriyA/gopAla-deshikaH/Ahnikam_AhnikArtha-prakAshikA/01_praveshaH.md
> +>> **स्वकीयेनात्मना** कर्त्रेति । **स्वशेषभूतेन** जीवेन प्रयोज्यकर्त्रेत्यर्थः ।
अत्र एकम् एव >-चिह्नं युज्यते। यतो नास्त्यत्रोद्धारे पुनरुद्धारः - प्रतीकग्रहनम् एव।

2022-12-02 08:28 UTC, vvasuki commented on AryaH/hinduism/branches/vaiShNavaH/shrI-sampradAyaH/kriyA/gopAla-deshikaH/Ahnikam_AhnikArtha-prakAshikA/01_praveshaH.md
> +> परगतातिशयाधानेच्छया उपादेयत्वमेव यस्य स्वरूपं स शेषः परश्शेषी
अत्र >> इति चिह्नद्वयं स्यात्।

2022-12-02 08:28 UTC, vvasuki commented on AryaH/hinduism/branches/vaiShNavaH/shrI-sampradAyaH/kriyA/gopAla-deshikaH/Ahnikam_AhnikArtha-prakAshikA/01_praveshaH.md
> +इति ।
एतद् उद्धारेऽन्तर्भवतीत्यवधेयम्।

2022-12-02 08:28 UTC, vvasuki commented on AryaH/hinduism/branches/vaiShNavaH/shrI-sampradAyaH/kriyA/gopAla-deshikaH/Ahnikam_AhnikArtha-prakAshikA/01_praveshaH.md
> +स्वकीयेनेत्यादौ प्रमाणसूचनाय सर्वशेषीत्याद्युक्तं - स्वयमेवेति आराध्यभूत एवाराधनं कारयतीति भावः । एवकारेण प्रवर्तकान्तरं च व्युदस्तम् । **कायती**ति । सर्वेश्वरस्सन् स्वेष्टं सर्वं स्वयमेव कर्तुं शक्त
एतद् उद्धारेऽन्तर्भवतीत्यवधेयम्।  अतो ऽत्र पूर्वतनरिक्तपङ्क्तौ च >-चिह्नं स्यात्.. 

"कर्तॄन् कारयतीति भावः ।" इत्यत्रोद्धरणं च समाप्यते।

2022-12-02 08:28 UTC, vvasuki commented on AryaH/hinduism/branches/vaiShNavaH/shrI-sampradAyaH/kriyA/gopAla-deshikaH/Ahnikam_AhnikArtha-prakAshikA/01_praveshaH.md
> +इति पारमेश्वरे त्रयोदशाध्याये
`इति। पारमेश्वरे त्रयोदशाध्याये -`

2022-12-07 05:48 UTC, Dhunee commented on AryaH/hinduism/branches/vaiShNavaH/shrI-sampradAyaH/kriyA/gopAla-deshikaH/Ahnikam_AhnikArtha-prakAshikA/01_praveshaH.md
> +>> **स्वकीयेनात्मना** कर्त्रेति । **स्वशेषभूतेन** जीवेन प्रयोज्यकर्त्रेत्यर्थः ।
ओम्

2022-12-07 05:48 UTC, Dhunee commented on AryaH/hinduism/branches/vaiShNavaH/shrI-sampradAyaH/kriyA/gopAla-deshikaH/Ahnikam_AhnikArtha-prakAshikA/01_praveshaH.md
> +> परगतातिशयाधानेच्छया उपादेयत्वमेव यस्य स्वरूपं स शेषः परश्शेषी
परिष्कृतम् ।

2022-12-07 05:49 UTC, Dhunee commented on AryaH/hinduism/branches/vaiShNavaH/shrI-sampradAyaH/kriyA/gopAla-deshikaH/Ahnikam_AhnikArtha-prakAshikA/01_praveshaH.md
> +इति ।
अस्पष्टम्

2022-12-07 05:49 UTC, Dhunee commented on AryaH/hinduism/branches/vaiShNavaH/shrI-sampradAyaH/kriyA/gopAla-deshikaH/Ahnikam_AhnikArtha-prakAshikA/01_praveshaH.md
> +स्वकीयेनेत्यादौ प्रमाणसूचनाय सर्वशेषीत्याद्युक्तं - स्वयमेवेति आराध्यभूत एवाराधनं कारयतीति भावः । एवकारेण प्रवर्तकान्तरं च व्युदस्तम् । **कायती**ति । सर्वेश्वरस्सन् स्वेष्टं सर्वं स्वयमेव कर्तुं शक्त
योजितम् । साधु न वेति सम्भ्रमः

2022-12-07 05:49 UTC, Dhunee commented on AryaH/hinduism/branches/vaiShNavaH/shrI-sampradAyaH/kriyA/gopAla-deshikaH/Ahnikam_AhnikArtha-prakAshikA/01_praveshaH.md
> +इति पारमेश्वरे त्रयोदशाध्याये
समीकृतम्

2022-12-07 06:17 UTC, vvasuki commented on AryaH/hinduism/branches/vaiShNavaH/shrI-sampradAyaH/kriyA/gopAla-deshikaH/Ahnikam_AhnikArtha-prakAshikA/01_praveshaH.md
> +> परगतातिशयाधानेच्छया उपादेयत्वमेव यस्य स्वरूपं स शेषः परश्शेषी
२९८-तम पङ्क्तौ कितः > > इति?

2022-12-07 06:18 UTC, vvasuki commented on AryaH/hinduism/branches/vaiShNavaH/shrI-sampradAyaH/kriyA/gopAla-deshikaH/Ahnikam_AhnikArtha-prakAshikA/01_praveshaH.md
> +> परगतातिशयाधानेच्छया उपादेयत्वमेव यस्य स्वरूपं स शेषः परश्शेषी
२९९-तमा पङ्क्तिर् उद्धारय् उद्धारः। ततः तस्यां  > > इति स्यात्।

2022-12-07 06:20 UTC, vvasuki commented on AryaH/hinduism/branches/vaiShNavaH/shrI-sampradAyaH/kriyA/gopAla-deshikaH/Ahnikam_AhnikArtha-prakAshikA/01_praveshaH.md
> +इति ।
२९५-तम-पङ्क्तौ `**स्वकीयेनात्मना** कर्त्रेति` इत्यनेन य उद्धार आरब्धः, तस्यैवेयम् अपि "इति"कारो ऽंशः। तेनोद्धरणचिह्नादिकम् अनुवर्तेत। अधोऽपि ३०१, ३०२ इत्यादिषु पङ्क्तिषु

2022-12-07 07:17 UTC, Dhunee commented on AryaH/hinduism/branches/vaiShNavaH/shrI-sampradAyaH/kriyA/gopAla-deshikaH/Ahnikam_AhnikArtha-prakAshikA/01_praveshaH.md
> +इति ।
ओम्

2022-12-07 07:52 UTC, vvasuki requested changes

2022-12-07 09:32 UTC, vvasuki requested changes

2022-12-27 12:41 UTC, Dhunee commented on AryaH/hinduism/branches/vaiShNavaH/shrI-sampradAyaH/kriyA/gopAla-deshikaH/Ahnikam_AhnikArtha-prakAshikA/01_praveshaH.md
ओम्

2022-12-27 12:41 UTC, Dhunee commented on AryaH/hinduism/branches/vaiShNavaH/shrI-sampradAyaH/kriyA/gopAla-deshikaH/Ahnikam_AhnikArtha-prakAshikA/01_praveshaH.md
> +> इति इदं तावदाप्रभातादानिशान्तमनुष्ठीयमानेषु सर्वेषु कर्मसु न विस्मर्तव्यं समयाचारनियमाध्यायश्रीवैष्णवधर्मशास्त्रादिकथितंपरमैकान्तिनां विशेषकर्तव्यं च सर्वं यथावदधिगन्तव्यम् । सर्वेषु च कर्मारम्भेषु
ओम्

2022-12-27 12:41 UTC, Dhunee commented on AryaH/hinduism/branches/vaiShNavaH/shrI-sampradAyaH/kriyA/gopAla-deshikaH/Ahnikam_AhnikArtha-prakAshikA/01_praveshaH.md
>  उपायतां परित्यज्य न्यस्येद्देवे तु तामभी: ॥
ओम्

2022-12-28 06:08 UTC, vvasuki commented on AryaH/hinduism/branches/vaiShNavaH/shrI-sampradAyaH/kriyA/gopAla-deshikaH/Ahnikam_AhnikArtha-prakAshikA/01_praveshaH.md
> +इति ।
uddharaṇē vartamānā riktapaṅktayō >-chnēnārabhēran. atra 301, 303 tamayōr anvēti.

2022-12-28 06:22 UTC, Dhunee commented on AryaH/hinduism/branches/vaiShNavaH/shrI-sampradAyaH/kriyA/gopAla-deshikaH/Ahnikam_AhnikArtha-prakAshikA/01_praveshaH.md
> +इति ।
नावगतम्

2022-12-28 07:28 UTC, vvasuki commented on AryaH/hinduism/branches/vaiShNavaH/shrI-sampradAyaH/kriyA/gopAla-deshikaH/Ahnikam_AhnikArtha-prakAshikA/01_praveshaH.md
> +इति ।
२९५-तम-पङ्क्तौ **स्वकीयेनात्मना** कर्त्रेति इत्यनेन य उद्धार आरब्धः, स ३०४-तमां यावद् अनुवर्तते। तन्मध्ये वर्तमानेषु रिक्तपङ्क्तिषु >-चिह्नम् भवेद् इति नियमः। स्पष्टम् वा?

2022-12-28 07:50 UTC, vvasuki requested changes
बहवो दोषा दृश्यन्ते। कृपया परिहृत्य +आद्यन्तम् पुनर् एकवारम् पठित्वा प्रेषयतु .

2022-12-28 07:50 UTC, vvasuki commented on AryaH/hinduism/branches/vaiShNavaH/shrI-sampradAyaH/kriyA/gopAla-deshikaH/Ahnikam_AhnikArtha-prakAshikA/01_praveshaH.md
> +> सत्यकाम, सत्यसङ्कल्प, सकलेतरविलक्षण, अर्थिकल्पक, आपत्सख, श्रीमन्नारायण, अणुपरिमाणदेहेन्द्रियादिविलक्षणज्ञानानन्दस्वरूपोऽहं, त्वदेकशेषस्त्वदेकनियाम्यस्त्वदेकाधारस्त्वदेकशरणस्त्वदेकप्राप्यकश्चास्मि
उद्धरणारम्भात् पूर्वं रिक्ता पङ्क्तिर् इष्यते।

2022-12-28 07:50 UTC, vvasuki commented on AryaH/hinduism/branches/vaiShNavaH/shrI-sampradAyaH/kriyA/gopAla-deshikaH/Ahnikam_AhnikArtha-prakAshikA/01_praveshaH.md
> +इति पारमेश्वरे त्रयोदशाध्याये -
`इति। ` - सदण्डम्।

2022-12-28 07:50 UTC, vvasuki commented on AryaH/hinduism/branches/vaiShNavaH/shrI-sampradAyaH/kriyA/gopAla-deshikaH/Ahnikam_AhnikArtha-prakAshikA/01_praveshaH.md
> +वचनतः प्रीणनमन्त्रेण कर्मसमर्पणं विहितं -
`विहितम्,` , अथवा `विहितम्।` वाक्य(खण्ड)-अन्तद्योतनाय।

2022-12-28 07:50 UTC, vvasuki commented on AryaH/hinduism/branches/vaiShNavaH/shrI-sampradAyaH/kriyA/gopAla-deshikaH/Ahnikam_AhnikArtha-prakAshikA/01_praveshaH.md
> +इति महाभारतवचनं सुसङ्गतं भवति - अत्र तु भाष्यकाराद्युक्तनित्यगद्यस्तोत्रादिषु यथानुसन्धानमुक्तं तत्सम्प्रदायनिष्ठैरनुसन्धेयम्
उद्धरणान्ते रिक्तपङ्क्तिर् इष्यते।

2022-12-28 07:50 UTC, vvasuki commented on AryaH/hinduism/branches/vaiShNavaH/shrI-sampradAyaH/kriyA/gopAla-deshikaH/Ahnikam_AhnikArtha-prakAshikA/01_praveshaH.md
> +> स्वकीयेनेत्यादौ प्रमाणसूचनाय सर्वशेषीत्याद्युक्तं -
`स्वकीयेनेत्यादौ प्रमाणसूचनाय सर्वशेषीत्याद्युक्तम्। ` इति वाक्यस्यान्तः।

2022-12-28 07:50 UTC, vvasuki commented on AryaH/hinduism/branches/vaiShNavaH/shrI-sampradAyaH/kriyA/gopAla-deshikaH/Ahnikam_AhnikArtha-prakAshikA/01_praveshaH.md
> +> स्वयमेवेति आराध्यभूत एवाराधनं कारयतीति भावः । एवकारेण प्रवर्तकान्तरं च व्युदस्तम् । **कायती**ति । सर्वेश्वरस्सन् स्वेष्टं सर्वं स्वयमेव कर्तुं शक्तोऽपि स्वशेषभूतजीवानां शास्त्रवश्यत्वतत्फलभोक्तृत्व
कायति? कारयतीति स्यात्?

2022-12-28 11:23 UTC, Dhunee commented on AryaH/hinduism/branches/vaiShNavaH/shrI-sampradAyaH/kriyA/gopAla-deshikaH/Ahnikam_AhnikArtha-prakAshikA/01_praveshaH.md
> +इति ।
आम्

2022-12-28 11:23 UTC, Dhunee commented on AryaH/hinduism/branches/vaiShNavaH/shrI-sampradAyaH/kriyA/gopAla-deshikaH/Ahnikam_AhnikArtha-prakAshikA/01_praveshaH.md
> +> सत्यकाम, सत्यसङ्कल्प, सकलेतरविलक्षण, अर्थिकल्पक, आपत्सख, श्रीमन्नारायण, अणुपरिमाणदेहेन्द्रियादिविलक्षणज्ञानानन्दस्वरूपोऽहं, त्वदेकशेषस्त्वदेकनियाम्यस्त्वदेकाधारस्त्वदेकशरणस्त्वदेकप्राप्यकश्चास्मि
ओम्

2022-12-28 11:23 UTC, Dhunee commented on AryaH/hinduism/branches/vaiShNavaH/shrI-sampradAyaH/kriyA/gopAla-deshikaH/Ahnikam_AhnikArtha-prakAshikA/01_praveshaH.md
> +इति सात्विकत्यागं कृत्वा
कृतम्

2022-12-28 11:23 UTC, Dhunee commented on AryaH/hinduism/branches/vaiShNavaH/shrI-sampradAyaH/kriyA/gopAla-deshikaH/Ahnikam_AhnikArtha-prakAshikA/01_praveshaH.md
> +इति पारमेश्वरे त्रयोदशाध्याये -
कृतम्

2022-12-28 11:24 UTC, Dhunee commented on AryaH/hinduism/branches/vaiShNavaH/shrI-sampradAyaH/kriyA/gopAla-deshikaH/Ahnikam_AhnikArtha-prakAshikA/01_praveshaH.md
> +वचनतः प्रीणनमन्त्रेण कर्मसमर्पणं विहितं -
कृतम्

2022-12-28 11:24 UTC, Dhunee commented on AryaH/hinduism/branches/vaiShNavaH/shrI-sampradAyaH/kriyA/gopAla-deshikaH/Ahnikam_AhnikArtha-prakAshikA/01_praveshaH.md
> +इति महाभारतवचनं सुसङ्गतं भवति - अत्र तु भाष्यकाराद्युक्तनित्यगद्यस्तोत्रादिषु यथानुसन्धानमुक्तं तत्सम्प्रदायनिष्ठैरनुसन्धेयम्
योजितम्

2022-12-28 11:24 UTC, Dhunee commented on AryaH/hinduism/branches/vaiShNavaH/shrI-sampradAyaH/kriyA/gopAla-deshikaH/Ahnikam_AhnikArtha-prakAshikA/01_praveshaH.md
> +समाधौ योगमेवैकं शाण्डिल्यस्सम मुक्तवान् ॥
परिष्कृतम्

2022-12-28 11:24 UTC, Dhunee commented on AryaH/hinduism/branches/vaiShNavaH/shrI-sampradAyaH/kriyA/gopAla-deshikaH/Ahnikam_AhnikArtha-prakAshikA/01_praveshaH.md
> +> स्वकीयेनेत्यादौ प्रमाणसूचनाय सर्वशेषीत्याद्युक्तं -
परिष्कृतम्

2022-12-28 11:24 UTC, Dhunee commented on AryaH/hinduism/branches/vaiShNavaH/shrI-sampradAyaH/kriyA/gopAla-deshikaH/Ahnikam_AhnikArtha-prakAshikA/01_praveshaH.md
> +> स्वयमेवेति आराध्यभूत एवाराधनं कारयतीति भावः । एवकारेण प्रवर्तकान्तरं च व्युदस्तम् । **कायती**ति । सर्वेश्वरस्सन् स्वेष्टं सर्वं स्वयमेव कर्तुं शक्तोऽपि स्वशेषभूतजीवानां शास्त्रवश्यत्वतत्फलभोक्तृत्व
परिष्कृतम् ।

2022-12-28 11:40 UTC, vvasuki commented
प्रमादेन काश्चन टिप्पन्यो ऽत्र प्रेषिताः - https://github.com/vishvAsa/AgamaH/commit/29e10f39b35927909aaad2d261ba20c7971aab91#comments । तेषां समाधानम् प्रश्ना वा तत्रैव यथास्थानं सूच्यन्ताम्।

2022-12-28 11:50 UTC, vvasuki requested changes

2022-12-28 11:50 UTC, vvasuki commented on AryaH/hinduism/branches/vaiShNavaH/shrI-sampradAyaH/kriyA/gopAla-deshikaH/Ahnikam_AhnikArtha-prakAshikA/01_praveshaH.md
>  >
इयम् पङ्क्तिर् व्यर्था।

2022-12-28 11:50 UTC, vvasuki commented on AryaH/hinduism/branches/vaiShNavaH/shrI-sampradAyaH/kriyA/gopAla-deshikaH/Ahnikam_AhnikArtha-prakAshikA/01_praveshaH.md
> +>युक्तस्वप्नावबोधस्य
>-चिह्नात् परम् एकं रिक्तस्थानम् अस्तु। एवं सर्वत्रारिक्तपङ्क्तिषु।

2022-12-28 12:03 UTC, Dhunee commented on AryaH/hinduism/branches/vaiShNavaH/shrI-sampradAyaH/kriyA/gopAla-deshikaH/Ahnikam_AhnikArtha-prakAshikA/01_praveshaH.md
> +>युक्तस्वप्नावबोधस्य
ओम्

2022-12-28 12:03 UTC, Dhunee commented on AryaH/hinduism/branches/vaiShNavaH/shrI-sampradAyaH/kriyA/gopAla-deshikaH/Ahnikam_AhnikArtha-prakAshikA/01_praveshaH.md
>  >
समीकृतम्

2022-12-28 12:05 UTC, vvasuki requested changes

2022-12-28 12:05 UTC, vvasuki commented on AryaH/hinduism/branches/vaiShNavaH/shrI-sampradAyaH/kriyA/gopAla-deshikaH/Ahnikam_AhnikArtha-prakAshikA/01_praveshaH.md
> +इति श्रीसूक्त्या श्रीभाष्यकाराव्यवहितशिष्यवङ्गिवंशेश्वररो[[??]]क्तप्रीणनमन्त्रान्तेन स्वनियाम्येत्यादिश्रीभाष्यकारवाक्येन समर्पणमेवाचार्यपादाभिमतमिति ज्ञायते । सहस्रनामभाष्ये “युधिष्ठिरश्शान्तनवं पुन
वङ्गिवंशेश्वरोक्त

2022-12-28 12:05 UTC, vvasuki commented on AryaH/hinduism/branches/vaiShNavaH/shrI-sampradAyaH/kriyA/gopAla-deshikaH/Ahnikam_AhnikArtha-prakAshikA/01_praveshaH.md
> +मू :- इति हरिशब्दार्थतया प्रसिद्धं समस्तपापहरं भगवन्तमनुसन्धाय, निद्रान्ताचमनं दक्षिणश्रवणस्पर्शरूपं वा तदानीं शक्यं विधाय, तस्मिन्नेव शयने आसीनः अखिलहेयप्रत्यनीककल्याणैकतान, स्वेनतर[[??]]समस्तवस्तुव
स्वेनतर[[??]]समस्तवस्तुविलक्षणानन्तज्ञानानन्दैकस्वरूप 
 
 इत्यस्य मूले दृश्यमानस्य चित्रं दर्शयतु।

2022-12-28 12:06 UTC, vvasuki commented on AryaH/hinduism/branches/vaiShNavaH/shrI-sampradAyaH/kriyA/gopAla-deshikaH/Ahnikam_AhnikArtha-prakAshikA/01_praveshaH.md
> +इति । न च भगवत्प्रभृतिस्वाचार्यपर्यन्तं तत्क्रमेण गुरुपङ्क्तिभजनं कार्यं “लक्ष्मीनाथसमारम्भां” कमप्याद्यं गुरुं वन्दे” इत्यादौ तथा दर्शनादाचाराच्चेति वाच्यम् - उक्ततृतीयाधिकारे “गुरून् प्रपद्य प्रथमं
एतत् परिष्कृतं वेत्यप्य् उररीकरोतु।

2022-12-28 12:09 UTC, vvasuki commented on AryaH/hinduism/branches/vaiShNavaH/shrI-sampradAyaH/kriyA/gopAla-deshikaH/Ahnikam_AhnikArtha-prakAshikA/01_praveshaH.md
> +मू :- इति हरिशब्दार्थतया प्रसिद्धं समस्तपापहरं भगवन्तमनुसन्धाय, निद्रान्ताचमनं दक्षिणश्रवणस्पर्शरूपं वा तदानीं शक्यं विधाय, तस्मिन्नेव शयने आसीनः अखिलहेयप्रत्यनीककल्याणैकतान, स्वेनतर[[??]]समस्तवस्तुव
"स्वानितर", "अतिशयौज्ज्वल्य"

2022-12-28 12:12 UTC, Dhunee commented on AryaH/hinduism/branches/vaiShNavaH/shrI-sampradAyaH/kriyA/gopAla-deshikaH/Ahnikam_AhnikArtha-prakAshikA/01_praveshaH.md
> +मू :- इति हरिशब्दार्थतया प्रसिद्धं समस्तपापहरं भगवन्तमनुसन्धाय, निद्रान्ताचमनं दक्षिणश्रवणस्पर्शरूपं वा तदानीं शक्यं विधाय, तस्मिन्नेव शयने आसीनः अखिलहेयप्रत्यनीककल्याणैकतान, स्वेनतर[[??]]समस्तवस्तुव
![image](https://user-images.githubusercontent.com/99737355/209810438-abd6342b-1ed7-4466-bb7a-74e259a4415c.png)

2022-12-28 12:14 UTC, Dhunee commented on AryaH/hinduism/branches/vaiShNavaH/shrI-sampradAyaH/kriyA/gopAla-deshikaH/Ahnikam_AhnikArtha-prakAshikA/01_praveshaH.md
> +इति । न च भगवत्प्रभृतिस्वाचार्यपर्यन्तं तत्क्रमेण गुरुपङ्क्तिभजनं कार्यं “लक्ष्मीनाथसमारम्भां” कमप्याद्यं गुरुं वन्दे” इत्यादौ तथा दर्शनादाचाराच्चेति वाच्यम् - उक्ततृतीयाधिकारे “गुरून् प्रपद्य प्रथमं
आम् । परिष्कृतम्

2022-12-28 12:17 UTC, vvasuki commented on AryaH/hinduism/branches/vaiShNavaH/shrI-sampradAyaH/kriyA/gopAla-deshikaH/Ahnikam_AhnikArtha-prakAshikA/01_praveshaH.md
> +मू :- इति हरिशब्दार्थतया प्रसिद्धं समस्तपापहरं भगवन्तमनुसन्धाय, निद्रान्ताचमनं दक्षिणश्रवणस्पर्शरूपं वा तदानीं शक्यं विधाय, तस्मिन्नेव शयने आसीनः अखिलहेयप्रत्यनीककल्याणैकतान, स्वेनतर[[??]]समस्तवस्तुव
प्रक्तनसन्देशयोर् यथोक्तं तथा समीकरोत्विह।

2022-12-28 12:19 UTC, Dhunee commented on AryaH/hinduism/branches/vaiShNavaH/shrI-sampradAyaH/kriyA/gopAla-deshikaH/Ahnikam_AhnikArtha-prakAshikA/01_praveshaH.md
> +मू :- इति हरिशब्दार्थतया प्रसिद्धं समस्तपापहरं भगवन्तमनुसन्धाय, निद्रान्ताचमनं दक्षिणश्रवणस्पर्शरूपं वा तदानीं शक्यं विधाय, तस्मिन्नेव शयने आसीनः अखिलहेयप्रत्यनीककल्याणैकतान, स्वेनतर[[??]]समस्तवस्तुव
समीकृतम्

2022-12-29 01:46 UTC, vvasuki commented
" द्वयोः मासयोरनन्तरं कार्यं चिकीर्षामि" इति सरयूः। तावद् दोषेषु सत्स्वपि यथाप्राप्तं स्वीकुर्वे।

2022-12-29 01:46 UTC, merged