Content
vishvAsa/AgamaH pull request #18
Opened 2022-12-08 14:40 UTC by Mansaram99

2022-12-08 14:43 UTC, vvasuki commented on AryaH/hinduism/branches/vaiShNavaH/shrI-sampradAyaH/kriyA/prayogamAlA/mUlam.md
> +### अग्निसंधानम्
पूर्वम् एवाग्निसन्धानम् इत्य् आगतो विभागः(८२९तमायाम्)। पुनर् अत्र कथम्?

2022-12-08 14:44 UTC, vvasuki commented on AryaH/hinduism/branches/vaiShNavaH/shrI-sampradAyaH/kriyA/prayogamAlA/mUlam.md
> +### *(आत्मसमारोपणम्)
शीर्षिकासु `(*)`आदिचिह्नानि न स्युः

2022-12-08 14:47 UTC, vvasuki commented on AryaH/hinduism/branches/vaiShNavaH/shrI-sampradAyaH/kriyA/prayogamAlA/mUlam.md
> +## दर्शपूर्णमासस्थालीपाकारंभकालविधिः
नैवम् प्राचीनापङ्क्तीर् निष्कासनीयाः। शीर्षिकापङ्क्तयो हि योजनीयाः। एवम् अन्यत्रापि। तथा हि, है स्यान् निरर्थक "विधि-विवरण"-सदृश-शब्दयोजनम्। 

https://github.com/vishvAsa/AgamaH/pull/18/files इत्यत्र व्यत्यासान् अभीक्ष्य समीकरोतु।

2022-12-10 13:02 UTC, Mansaram99 commented on AryaH/hinduism/branches/vaiShNavaH/shrI-sampradAyaH/kriyA/prayogamAlA/mUlam.md
> +### अग्निसंधानम्
अत्र भ्रमान्मया कृतमेतत् । अत्र पृष्ठशीर्षकं भ्रमात् शीर्षकं रूपेण प्रदत्तम् ।

2022-12-10 13:02 UTC, Mansaram99 commented on AryaH/hinduism/branches/vaiShNavaH/shrI-sampradAyaH/kriyA/prayogamAlA/mUlam.md
> +### *(आत्मसमारोपणम्)
अत्रापि मयैव दोषो जातः

2022-12-10 13:04 UTC, Mansaram99 commented on AryaH/hinduism/branches/vaiShNavaH/shrI-sampradAyaH/kriyA/prayogamAlA/mUlam.md
> +## दर्शपूर्णमासस्थालीपाकारंभकालविधिः
इतः परं न भविष्यति महोदय

2022-12-10 13:27 UTC, vvasuki requested changes

2022-12-10 13:27 UTC, vvasuki commented on AryaH/hinduism/branches/vaiShNavaH/shrI-sampradAyaH/kriyA/prayogamAlA/mUlam.md
> +### अत्रि:
प्राणायामे ऽयम् आपतति ग्रन्थान्तरोल्लेखः, न पृथग् विभागः। तेन विभागचिह्नानि "###" इति मा भूत्। एवम् अन्यत्र।

2022-12-10 13:27 UTC, vvasuki commented on AryaH/hinduism/branches/vaiShNavaH/shrI-sampradAyaH/kriyA/prayogamAlA/mUlam.md
> +### वैकुण्ठदीक्षितीये
न पृथग् विभागः। तेन विभागचिह्नानि "###" इति मा भूत्। एवम् अन्यत्र।

2022-12-10 13:27 UTC, vvasuki commented on AryaH/hinduism/branches/vaiShNavaH/shrI-sampradAyaH/kriyA/prayogamAlA/mUlam.md
> +### द्वातिंशुदुपचारक्रमः (३२)
द्वात्रिंशद् इति स्यात् खलु?

2022-12-10 13:27 UTC, vvasuki commented on AryaH/hinduism/branches/vaiShNavaH/shrI-sampradAyaH/kriyA/prayogamAlA/mUlam.md
> +### * गृहप्रोक्षणमन्त्राः
विभागेषु *-आदि-चिह्नानि न स्युः। एवं सर्वत्र परिहृत्यात्र "परिहृतम्" इति सूचयतु।

2022-12-10 13:27 UTC, vvasuki commented on AryaH/hinduism/branches/vaiShNavaH/shrI-sampradAyaH/kriyA/prayogamAlA/mUlam.md
> +## दर्शपूर्णमासस्थालीपाकारंभकालविधिः
इतः परं न भवतु नाम, सद्यः कृतम् परिष्कृतं वा? नेति भाति।

2022-12-10 13:27 UTC, vvasuki commented on AryaH/hinduism/branches/vaiShNavaH/shrI-sampradAyaH/kriyA/prayogamAlA/mUlam.md
> +### *(आत्मसमारोपणम्)
दोषो जातश् चेत् यथोक्तं सर्वत्र परीक्ष्य परिहरणीयं खलु?

2022-12-12 08:58 UTC, Mansaram99 commented on AryaH/hinduism/branches/vaiShNavaH/shrI-sampradAyaH/kriyA/prayogamAlA/mUlam.md
> +### अत्रि:
आम् महोदय , तत्र मया एतयोः शीर्षकरूपेण चि्न्तितम् तस्मादेव ### इति प्रदत्तम् 
मया शोधनं कृतम्

2022-12-12 09:05 UTC, Mansaram99 commented on AryaH/hinduism/branches/vaiShNavaH/shrI-sampradAyaH/kriyA/prayogamAlA/mUlam.md
> +### वैकुण्ठदीक्षितीये
अस्तु महोदय । इतः परं न भवेत्
अत्र मम कारणात् एव दोषम् अजायत्

2022-12-12 09:13 UTC, Mansaram99 commented on AryaH/hinduism/branches/vaiShNavaH/shrI-sampradAyaH/kriyA/prayogamAlA/mUlam.md
> +### * गृहप्रोक्षणमन्त्राः
विभागेंंषु नास्ति परन्तु महोदय पुस्तकमन्तरेणास्ति तम्सादेव कृतम्

2022-12-12 09:30 UTC, Mansaram99 commented on AryaH/hinduism/branches/vaiShNavaH/shrI-sampradAyaH/kriyA/prayogamAlA/mUlam.md
> +### * गृहप्रोक्षणमन्त्राः
परिहृतम्

2022-12-12 16:32 UTC, Mansaram99 commented on AryaH/hinduism/branches/vaiShNavaH/shrI-sampradAyaH/kriyA/prayogamAlA/mUlam.md
> +### *(आत्मसमारोपणम्)
आम् महोदय सर्वत्रैव क्रियते

2022-12-12 17:17 UTC, Mansaram99 commented on AryaH/hinduism/branches/vaiShNavaH/shrI-sampradAyaH/kriyA/prayogamAlA/mUlam.md
> +### वैकुण्ठदीक्षितीये
प्रयोगमालायां एव आसीत् 
अहं तु स्वस्मदेव तत् निष्काषितम् 
प्रयोगमालायां इति पुनः शोधतिम्

2022-12-13 01:57 UTC, vvasuki commented on AryaH/hinduism/branches/vaiShNavaH/shrI-sampradAyaH/kriyA/prayogamAlA/mUlam.md
> +### *(आत्मसमारोपणम्)
सर्वत्रैव कृत्वा रक्षित्वाऽत्र सूचयतु, येनाहम् परीक्ष्योररीकुर्याम्।

2022-12-13 01:58 UTC, vvasuki commented on AryaH/hinduism/branches/vaiShNavaH/shrI-sampradAyaH/kriyA/prayogamAlA/mUlam.md
> +## दर्शपूर्णमासस्थालीपाकारंभकालविधिः
कुत्र परिष्कृतम्? अस्यां सञ्चिकायाम् अन्यत्र त एव दोषा दृश्यन्ते। सर्वत्रैव कृत्वा रक्षित्वाऽत्र सूचयतु, येनाहम् परीक्ष्योररीकुर्याम्।

2022-12-13 01:59 UTC, vvasuki commented on AryaH/hinduism/branches/vaiShNavaH/shrI-sampradAyaH/kriyA/prayogamAlA/mUlam.md
> +### अत्रि:
यावद् भवान् शोधितम् पाठं न रक्षति, तावत् "शोधनं कृतम्" इत्यादि न लिखेत् - यतो हि नाहं शोधितं न वेति परीक्षितुं शक्नोमि …

2022-12-13 02:03 UTC, vvasuki commented on AryaH/hinduism/branches/vaiShNavaH/shrI-sampradAyaH/kriyA/prayogamAlA/mUlam.md
> +### द्वातिंशुदुपचारक्रमः (३२)
द्वातिंशद् इति स्याद् वा द्वात्रिंशद् इति स्याद् वा? भवता नूतनाः शुद्धाः पङ्क्तयो योजनीयाः, न पुरातन्यः परिवर्तनीयाः।  एवं सर्वत्रैव कृत्वा रक्षित्वाऽत्र सूचयतु, येनाहम् परीक्ष्योररीकुर्याम्।

2022-12-13 02:04 UTC, vvasuki commented on AryaH/hinduism/branches/vaiShNavaH/shrI-sampradAyaH/kriyA/prayogamAlA/mUlam.md
> +### * गृहप्रोक्षणमन्त्राः
यावद् भवान् शोधितम् पाठं न रक्षति, तावत् "शोधनं कृतम्" इत्यादि न लिखेत् - यतो हि नाहं शोधितं न वेति परीक्षितुं शक्नोमि …

2022-12-13 13:00 UTC, Mansaram99 commented on AryaH/hinduism/branches/vaiShNavaH/shrI-sampradAyaH/kriyA/prayogamAlA/mUlam.md
> +### *(आत्मसमारोपणम्)
परिष्कृतम् महोदय

2022-12-13 13:00 UTC, Mansaram99 commented on AryaH/hinduism/branches/vaiShNavaH/shrI-sampradAyaH/kriyA/prayogamAlA/mUlam.md
> +## दर्शपूर्णमासस्थालीपाकारंभकालविधिः
परिष्कृतं महोदय

2022-12-13 13:01 UTC, Mansaram99 commented on AryaH/hinduism/branches/vaiShNavaH/shrI-sampradAyaH/kriyA/prayogamAlA/mUlam.md
> +### अत्रि:
शोधितम्

2022-12-13 13:04 UTC, Mansaram99 commented on AryaH/hinduism/branches/vaiShNavaH/shrI-sampradAyaH/kriyA/prayogamAlA/mUlam.md
> +### द्वातिंशुदुपचारक्रमः (३२)
द्वातिंशुदुपचाराः 
आम् महोदय

2022-12-13 13:06 UTC, Mansaram99 commented on AryaH/hinduism/branches/vaiShNavaH/shrI-sampradAyaH/kriyA/prayogamAlA/mUlam.md
> +### * गृहप्रोक्षणमन्त्राः
अस्तु  महोदय

2022-12-16 01:24 UTC, merged